sonar.projectKey=jexxa-projects_CLegMed
sonar.organization=jexxa-projects

sonar.sources=include
sonar.tests=tests

sonar.cfamily.skipAnalysisOfUnindexedFiles=true

sonar.cfamily.headerRequirement=All

sonar.coverage.exclusions=tests/**
