sonar.projectKey=jexxa-projects_CLegMed
sonar.organization=jexxa-projects

# 1. Das gesamte Projekt als Basis-Quelle definieren
sonar.sources=.

# 2. WICHTIG: Den Test-Ordner explizit aus den 'sources' ausschließen!
# Das verhindert den "can't be indexed twice" Fehler.
sonar.exclusions=tests/**, build/**, bw-output/**, .github/**

# 3. Den Tests-Ordner separat als offiziellen Testcode deklarieren
sonar.tests=tests

# 4. Erlaubt SonarCloud, die .cpp-Dateien aus dem Testordner im Hintergrund
# für den Build-Wrapper zu nutzen, obwohl sie aus den sources ausgeschlossen sind.
sonar.cfamily.skipAnalysisOfUnindexedFiles=true

# 5. Header-Analyse für Ihren include-Ordner erzwingen
sonar.cfamily.headerRequirement=All

# 6. Abdeckungs-Statistik rein auf das Framework beschränken
sonar.coverage.exclusions=**
sonar.coverage.inclusions=include/**
