sonar.projectKey=jexxa-projects_CLegMed
sonar.organization=jexxa-projects

# 1. Hauptquelle ist nur der include-Ordner (enthält jetzt die Dummy-.cpp)
sonar.sources=include

# 2. Die Tests sauber separieren
sonar.tests=tests

# 3. Alle Header im include-Ordner zur Analyse zwingen
sonar.cfamily.headerRequirement=All

# 4. Coverage rein auf die echten Header im include-Ordner beschränken
sonar.coverage.exclusions=tests/**
