name: SonarQube
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones disabled for better analysis relevancy

      - name: Setup CMake 4
        uses: jwlawson/actions-setup-cmake@0d6a7d60b009d01c9e7523be22153ff8f19460d3
        with:
          cmake-version: '4.x'

      # 1. System-Tools und GCC 14 + Gcov 14 installieren
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc-14 g++-14 gcovr

      # 2. SonarCloud Build Wrapper installieren
      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@713881670b6b3676cda39549040e2d88c70d582e

      - name: Set Build Directory
        id: strings
        shell: bash
        run: echo "build-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      # 3. CMake konfigurieren (mit -O0 -g Flags zur Behebung von Release-Optimierungsproblemen)
      - name: Configure CMake
        run: >
          cmake -B ${{ steps.strings.outputs.build-dir }}
          -DCMAKE_CXX_COMPILER=g++-14
          -DCMAKE_C_COMPILER=gcc-14
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_CXX_STANDARD=23
          -DCMAKE_CXX_STANDARD_REQUIRED=ON
          -DCMAKE_CXX_FLAGS="--coverage -O0 -g"
          -S ${{ github.workspace }}

      # 4. Projekt kompilieren (WICHTIG: Wieder in den Build Wrapper eingepackt!)
      - name: Build Project
        run: |
          build-wrapper-linux-x86-64 --out-dir bw-output cmake --build ${{ steps.strings.outputs.build-dir }} --config Release

      # 5. Tests ausführen
      - name: Run Tests
        working-directory: ${{ steps.strings.outputs.build-dir }}
        run: ctest --build-config Release

      # 6. Coverage-Bericht generieren (Mit gcov-14 Fix, Ausschluss von Drittanbieter-Code und default-Methoden-Filter)
      - name: Generate Coverage Report
        run: |
          gcovr --exclude-throw-branches --exclude-unreachable-branches --sonarqube build/coverage.xml \
            -r . \
            --object-directory ${{ steps.strings.outputs.build-dir }} \
            --gcov-executable gcov-14 \
            --gcov-ignore-errors=no_working_dir_found \
            --exclude-lines-by-pattern '.*=\s*default\s*;' \
            --exclude '.*/_deps/.*' \
            --exclude '.*/CMakeFiles/.*' \
            --exclude '.*/tests/.*'


      # 7. SonarCloud Scan ausführen und die generierten Berichte übergeben
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@713881670b6b3676cda39549040e2d88c70d582e
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.cfamily.compile-commands=bw-output/compile_commands.json
            -Dsonar.coverageReportPaths=build/coverage.xml
